In [1]:
import numpy as np

In [43]:
arr=np.array([[-1,2,0,4],
             [4,-0.5,6,0],
             [2.6,0,7,8],[3,-7,4,2.0]],)

In [44]:
temp=arr[:1,::1]

In [45]:
temp

array([[-1,  2,  0,  4]])

In [46]:
arr.max()

8

In [47]:
arr.max(axis=1)

array([4, 6, 8, 4])

In [52]:
res=arr.mean(axis=1,dtype='int')

In [55]:
res

array([1, 2, 4, 0])

In [56]:
kim=list(res)

In [57]:
kim

[1, 2, 4, 0]